### env config ###

image: Visual Studio 2015

# jsd: cuts down about 10 seconds of build
clone_depth: 1

### build config ###
version: 0.7.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: RelWithDebInfo
cache:
  - build\SDL2-devel-2.0.5-VC.zip
  - build\SDL2-2.0.5
  - build\SDL2_mixer-devel-2.0.1-VC.zip
  - build\SDL2_mixer-2.0.1
build:
  project: build\Odamex.sln
  verbosity: minimal
  parallel: true
before_build:
  - ps: .\appveyor_before_build.ps1
after_build:
  - ps: .\appveyor_after_build.ps1

### artifacts config ###

artifacts:
  - path: odamex.zip
  - path: odasrv.zip